---
- name: copy circus config
  copy: src=circus.ini dest=/etc/circus.ini
  notify: restart circus


- name: copy nginx config
  tags: nginx
  template: src=nginx.conf dest=/usr/local/nginx/conf/nginx.conf
  notify: reload nginx

- name: validate nginx config
  tags: nginx
  shell: /usr/local/nginx/sbin/nginx -t

- name: start nginx
  service: name=nginx state=started


- name: copy sources
  command: rsync -az
           ../package.json
           ../lib
           ../hashwick-server
           ../hashwick-webapp
           ../vendor
           {{ ansible_user_id }}@{{ inventory_hostname }}:/srv/hashwick
  delegate_to: localhost
  notify: restart hashwick-server

- name: npm install
  shell: cd /srv/hashwick && npm install

- name: copy config.production.json
  template: src=config.production.json dest=/srv/hashwick/hashwick-server/config.production.json
  notify: restart hashwick-server
