---
- name: create user
  user: name=packrat shell=/bin/false

- name: create database
  shell: |
    sudo -u postgres psql <<EOF
      CREATE DATABASE packrat;
      CREATE USER packrat WITH PASSWORD '{{ db_password }}';
      GRANT ALL PRIVILEGES ON DATABASE packrat TO packrat;
    EOF

- name: create app directory
  file: path=/srv/hashwick state=directory owner=packrat
