---
- hosts:
    - packrat
    - webapp
  roles:
    - common
    - circus

- hosts:
    - packrat
  vars_files: [roles/packrat/vars/secrets.yml]
  roles:
    - packrat

- hosts:
    - webapp
  vars_files: [roles/webapp/vars/secrets.yml]
  roles:
    - webapp
