---
- name: system packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - make
    - g++
    - gcc
    - libpcre3-dev
    - zlib1g-dev
    - libbz2-dev
    - libssl-dev
    - libreadline6-dev
    - libsqlite3-dev
    - libevent-dev
    - python2.7
    - python2.7-dev
    - postgresql
    - postgresql-server-dev-9.1

- name: install pip
  shell: cd /tmp
         && curl https://bootstrap.pypa.io/get-pip.py | python
         creates=/usr/local/bin/pip

- name: build node.js
  shell: cd /tmp
         && curl http://nodejs.org/dist/v0.10.18/node-v0.10.18.tar.gz | tar xz
         && cd node-*
         && ./configure && make && make install
         creates=/usr/local/bin/node

- name: build nginx
  shell: cd /tmp
         && curl http://nginx.org/download/nginx-1.5.5.tar.gz | tar xz
         && cd nginx-*
         && ./configure && make && make install
         creates=/usr/local/nginx

- name: nginx init script
  copy: src=nginx.init dest=/etc/init.d/nginx mode=0755
