---
- name: copy circus config
  copy: src=circus.ini dest=/etc/circus.ini
  notify: restart circus


- name: copy sources
  command: rsync -az
           ../package.json
           ../lib
           ../packrat
           {{ ansible_user_id }}@{{ inventory_hostname }}:/srv/hashwick
  delegate_to: localhost
  notify: restart packrat

- name: create schema
  shell: sudo -u packrat psql packrat < /srv/hashwick/packrat/db/2013-11-03.sql

- name: npm install
  shell: cd /srv/hashwick && npm install --production

- name: copy config.production.json
  template: src=config.production.json dest=/srv/hashwick/packrat/config.production.json
  notify: restart packrat
